### ISSUE TITLE
Best way to make a cross-platform GUI app in Zig?

### ISSUE THREAD

**Issue by TUSF** [nektro/zigquestions#1]

**Comment by nektro** [comment]
there are many fledgling tools to accomplish this task and the best one to choose will all depend on your specific goals. below is a selection of some currently being worked on:

GUI Toolkits

-    https://github.com/capy-ui/capy Cross-platform library for native GUIs, in Zig.
-    https://github.com/MasterQ32/zero-graphics Application framework based on OpenGL ES 2.0. Desktop, Mobile & Web Support
-    https://github.com/david-vanderson/dvui Easy to Integrate Immediate Mode GUI for Zig
-    https://machengine.org/ Game engine & graphics toolkit for the future, built around WebGPU.
-    https://github.com/fubark/cosmic A platform for computing and creating applications. Includes standalone graphics library & ui engine.
-    https://github.com/cztomsik/graffiti HTML/CSS engine for node.js and deno.
-    https://sr.ht/~nektro/magnolia-desktop/ A new desktop environment / UI toolkit for Linux

GUI Toolkit Bindings

-    https://github.com/michal-z/zig-gamedev/tree/main/libs/zgui Easy to use dear imgui bindings. (WebGPU backend by default)
-    https://github.com/desttinghim/zig-libui-ng Zig bindings for libui-ng.
-    https://github.com/batiati/IUPforZig Zig idiomatic and type-checked bindings for IUP Portable User Interface Toolkit.
-    https://github.com/kassane/qml_zig QML bindings. (based on DOtherSide C bindings)
-    https://github.com/MoAlyousef/zfltk Zig bindings for the FLTK gui library
-    https://github.com/ianprime0509/zig-gobject (WIP) GObject bindings for Zig 

Graphics Libraries

-    https://github.com/fabioarnold/nanovg-zig Hardware-accelerated (OpenGL+WebGL) vector graphics library, rewritten in Zig
-    https://github.com/dweiller/nanovg-zig/tree/mach-backend Mach WebGPU backend for nanovg-zig.

Component/Other Libraries

-    https://github.com/star-tek-mb/zig-tray Create tray applications with zig.
 -   https://github.com/hexops/harfbuzz A fork of harfbuzz packaged for the Zig build system
-    https://github.com/hexops/freetype A fork of freetype packaged for the Zig build system

**Comment by raspberrypisig** [comment]
That's a great list!

Normally, I don't write immediate mode gui apps.

I recently decided to build a simple tool.
Initially, I was tempted to go with the libui-ng binding for zig(the one mentioned in the list above, which is great), because of native controls on Windows, linux(raspberry pi) and Mac.

But then I realised that native controls are very restricted in terms of layout and styling and especially forms tend to be two column chock full of controls(like the controls suite examples, suited to something like Rufus style apps).

Then I stumbled over raygui, a sister project of raylib. There are a number of free GUI tools that the author has created(eg. RGuiStyler) for doing things like creating custom styles, icons etc.

raygui has a number of bindings for various languages. I eventually ended up writing the tool using the python binding because of the changes in the build system in the latest zig master, but the zig binding (https://github.com/ryupold/raygui.zig) is good too when they get that working again.
(https://github.com/ryupold/examples-raylib.zig/issues/12)

One thing to note is that they keep examples in a separate repo to the binding project under the same author.
