### ISSUE TITLE
Questions about alignment, memory addresses and hexadecimal numbers

### ISSUE THREAD

**Issue by nacho00112** [nektro/zigquestions#11]
I'm a python developer trying to learn zig to learn low-level programming with zig, I didn't liked C, it has a very large amount of constants that I have to memorize in its libc.
I don't have knowledge about low-level programming, the language reference seems to assume that I have, so I'm gonna ask about what I don't get here.

Before telling you the questions, to help you to answer better them, here is a list of
what I think I understand about zig, please correct me if I'm wrong:
- 1 bit = something like `true` and `false`.
- 1 byte = 8 bits.
- maximum number size = 2 ^ (BYTES × 8).
- numbers are a combination of bits, though I don't know the pattern, for example I don't know what is the bit representation for the number `10` in 8 bits, please explain to me if possible.
- a pointer is a hexadecimal number that is the identifier of some data, though we need `@intFromPtr` to get that number.
- a hexadecimal number is `1.6 × hexadecimal number` 11-16 is represented by abecedary letters.
- the purpose of pointers is to change multiple variables at the same time like this:

`pointers.zig`:
```zig
const std = @import("std");
const print = std.debug.print;
test "pointers" {
 var var1: i32 = 10;
 var var2: *i32 = &var1;
 var2.* = 20;
 print("{}", .{var1}); // Output: 20
}
```
```bash
zig test pointers.zig
```
```
20
```

here are my questions, they are quite a few, besides of those related to the title of the issue, I added some miscellanious questions too.

- Question 1: in which cases the hexadecimal numbers are used in memory management? why? I mean why base 16 representation is so useful here?
- Question 2: what is Alignment and align() exactly? what is its use? please explain me from the most basic thing, I have no idea what alignment is.
- Question 3: In the language reference, in the Alignment section, it says that the memory address of the data must be evenly divisible by the specified "alignment", why? the memory address wasn't simply an identifier? what is the memory address exactly? how it is determined?
- Question 4: also that section seems to use `std.mem.sliceToBytes` and `std.mem.bytesToSlice`, that made me everything harder to understand, the standard library documentation is not clear enough to me too, please explain me what those function do?
- Question 5: when they say "a slice or pointer" with pointer they refer to that alternative to get elements from an array?
- Question 6: when they say that a constant is defined at compile time they refer to that the variable have only one runtime assignment determined at compile time instead of various ones? or that the constant assignment is executed at compile time like I'm using comptime?
- Question 7: If I add comptime var, that means that all the assignments of that variable are executed at compile time and the references to it are evaluated at compile time according to the assignments? if it is so the fact that it is used like a normal variable but it is not seems a bit implicit to me though.

As I said, I have no prior low-level programming experience, so please treat me as a beginner that does know nothing besides the things I said I think that I understand.

**Comment by nektro** [comment]
regarding the binary representation of integers, a great explanation and visualization can be found here https://youtu.be/QZwneRb-zqA?t=306. Zig uses the same system.

a short explanation of memory and zig's types that i love can be found here https://gist.github.com/lobre/4fbf32961513784dde2a9ef4e6a4a1d9

1. since the smallest unit that can be addressed in RAM is the byte, hexadecimal is commonly used since 2 hexadecimal digits can cleanly represent 256 values which is the same as a u8/byte
2. `align(5)` means the address of that value (if you were to do `@intFromPtr` on it) would be a multiple of 5. aligning slice/array elements to a specific multiple is required for some operations. it's not very common to use/need so i'm not familiar with any off the top of my head
3. this should mostly be covered by my previous answer and the two resources i posted above, feel free to ask for followup
4. `std.mem.toBytes` converts a value that has a size that is a multiple of `u8` and coverts it into an array. so for example u can convert a `u32` into a `[4]u8`.
5. covered by resource 2
6. a `const` defined at file/container scope will be evaluated always at comptime yes. a `const` inside a function will be evaluated at comptime only if its not a function or if it is prefixed with the `comptime` keyword. regardless of position `const` means the value cannot be changed
7. the benefit of `comptime var` is that the resulting value inside the compiled binary will be as if you had written a literal, whereas a regular `var` you would see an add assembly instruction

hope this helps! feel free to ask any clarifying questions and congrats on giving Zig a try, happy to have you here :D

**Comment by nektro** [comment]
as an added bonus since i just love this video, a great explainer on the representation Zig uses for floats can be found here https://www.youtube.com/watch?v=dQhj5RGtag0
