### ISSUE TITLE
How to create ANSI `/SUBSYSTEM WINDOS` program without build system or CLI flags?

### ISSUE THREAD

**Issue by expikr** [nektro/zigquestions#22]
when attempting to use `WinMain` the compiler errors saying that only wWinMain or main is supported.

However, wWinMain creates a UTF16 program.

If I use `main` instead then it launches a black console box on startup, you'd need to explictly set `--subsystem windows` to make it compile as a GUI program.

Is there any way that lets you `zig run main.zig` that compiles with the GUI subsystem by default without also being forced to onto UTF16?

cc @squeek502

**Comment by squeek502** [comment]
A few things to note:

- The main function is only used to determine [the entry point](https://learn.microsoft.com/en-us/cpp/build/reference/entry-entry-point-symbol?view=msvc-170). That is, in a C program, the entry point is chosen out of some symbols that are defined by the C runtime (`mainCRTStartup`, `wmainCRTStartup`, `WinMainCRTStartup`, `wWinMainCRTStartup`), and which `main` function is defined is used to determine which entry point to use.
  + This is loosely but not directly related to the subsystem AFAIK. If the subsystem is not chosen explicitly, then the linker also infers the subsystem via the main function (note that this is currently regressed in Zig when targeting MinGW: https://github.com/ziglang/zig/issues/18621)
- In Zig, the startup code in `std/start.zig` handles the code and the choosing of the entry point (it does not use/rely on the C runtime symbols), so in Zig code using `main` vs `wWinMain` are only different in that ~~defining `wWinMain` makes Zig infer `--subsystem windows`~~ (see https://github.com/ziglang/zig/issues/17808 for some complication around this)
  + EDIT: I misremembered the implications of https://github.com/ziglang/zig/issues/17808. Right now, Zig effectively always infers `console` subsystem, since it exports `wWinMainCRTStartup` for both `main` and `wWinMain`. So, if you want your program to have the `windows` subsystem in the PE/COFF binary, you will basically have to set `--subsystem` explicitly.
    + This is something I have a local branch to attempt to address but it got complicated quick and I haven't worked on it recently
- Using `wWinMain` does not "create a UTF16 program" or "force you onto UTF-16," it just means that the command line arguments will be provided as WTF-16, which is the native encoding for command line arguments (the C runtime would have to do some lossy conversion from WTF-16 before calling your `main`/`WinMain` function).

My suggestion is to take a look at Zig's entry point handling of `wWinMain` in `start.zig`, in particular:

https://github.com/ziglang/zig/blob/7ecbb6f3a07743669590f0c0e1767f49c7ca1fc3/lib/std/start.zig#L73-L77

https://github.com/ziglang/zig/blob/7ecbb6f3a07743669590f0c0e1767f49c7ca1fc3/lib/std/start.zig#L353-L363

https://github.com/ziglang/zig/blob/7ecbb6f3a07743669590f0c0e1767f49c7ca1fc3/lib/std/start.zig#L533-L565

You can then compare it to the entry point when using `main`:

https://github.com/ziglang/zig/blob/7ecbb6f3a07743669590f0c0e1767f49c7ca1fc3/lib/std/start.zig#L342-L351

There's very little magic involved and I think it'll improve your understanding of what's going on.

**Comment by squeek502** [comment]
As far as I know, `UNICODE` is an entirely separate concept. It's usually a good idea to define `UNICODE` when using `wWinMain`/`wmain` but not required/implicit (I think it's not really possible for it to be, since `UNICODE` is a preprocessor concept while the entry point/subsystem is a linker concept).

**Comment by squeek502** [comment]
UTF-8 is weird, you have to embed a manifest in your binary to enable it: https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page and then use the `-A` suffixed functions.

Zig now has support for `.manifest` files, see https://www.ryanliptak.com/blog/zig-is-a-windows-resource-compiler/#manifest-files

You'd have to test what `main`/`WinMain` gives you for command line args when you embed the manifest, I'm not sure how/if that interacts. Some other caveats are detailed here: https://github.com/ziglang/zig/issues/534#issuecomment-1784234858
